api_platform:
    title: Quiz API
    version: 0.1-alpha

    allow_plain_identifiers: true # So we can use normal json objects with id instead of ld+json, no need for complexer json structure in this app

    resource_class_directories: # Where api-platform can find the entities that are resources
        - '%kernel.project_dir%/config/api_platform/entities/'

    # Enable the Varnish integration
#    http_cache:
#        invalidation:
#            enabled: false
#            varnish_urls: ['%env(VARNISH_URL)%']
#        max_age: 0
#        shared_max_age: 0
#        vary: ['Content-Type', 'Authorization']
#        public: true

    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']