api_platform:
    title: Quiz API
    version: 0.1-alpha

#    allow_plain_identifiers: true # So we can use normal json objects with id instead of ld+json, no need for complexer json structure in this app

    resource_class_directories: # Where api-platform can find the entities that are resources
        - '%kernel.project_dir%/config/api_platform/entities/'


    collection:
        pagination:
            enabled: false
            client_enabled: true
            enabled_parameter_name: paginate

    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header