security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        auth:
            pattern: ^/api/auth
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/auth/login_check
                username_path: email
                password_path: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            provider: user_provider
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #Entity ACL

        - { path: ^/api/auth, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }

    role_hierarchy:
        ROLE_STUDENT: ROLE_USER
        ROLE_TEACHER: ROLE_USER
        ROLE_ADMIN: ROLE_USER

