App\Entity\Activity:
    collectionOperations:
        post:
            normalization_context:
                groups: ["activity.post"]
            denormalization_context:
                groups: ["activity.post"]

    itemOperations:
        get:
            access_control: "user.hasAccessToQuiz(object.getSession().getQuiz()) or has_role('ROLE_ADMIN')"