App\Entity\Answer:
    collectionOperations:
        post:
            access_control: "user.hasAccessToQuiz(object.getQuestion().getQuiz())"
            normalization_context:
                groups: ["answer.post"]

    itemOperations:
        get:
            access_control: "user.hasAccessToQuiz(object.getQuestion().getQuiz())"
        delete:
            access_control: "user.hasAccessToQuiz(object.getQuestion().getQuiz())"
        put:
            access_control: "user.hasAccessToQuiz(object.getQuestion().getQuiz())"
            normalization_context:
                groups: ["answer.get"]
            denormalization_context:
                groups: ["answer.put"]