App\Entity\Answer:
    collectionOperations:
        get: ~
        post:
            normalization_context:
                groups: ["answer.post"]

    itemOperations:
        get: ~
        delete: ~
        put:
            normalization_context:
                groups: ["answer.get"]
            denormalization_context:
                groups: ["answer.put"]