App\Entity\Question:
    collectionOperations:
        get: ~
        post:
            normalization_context:
                groups: ["question.post"]
    itemOperations:
        get: ~
        put:
            normalization_context:
                groups: ["question.get"]
            denormalization_context:
                groups: ["question.put"]

        delete: ~

