App\Entity\Quiz:
    attributes:
        normalization_context:
            enable_max_depth: true
        denormalization_context:
            enable_max_depth: true

    collectionOperations:
        get:
            normalization_context:
                enable_max_depth: true
                groups: ["quizzes.get"]
        post: ~
    itemOperations:
        get:
            normalization_context:
                enable_max_depth: true
                groups: ["quiz.get"]
        put:
            normalization_context:
                enable_max_depth: true
                groups: ["quiz.put"]
            denormalization_context:
                enable_max_depth: true
                groups: ["quiz.put"]

        delete: ~