App\Entity\Session:
    collectionOperations:
        get: ~
        post:
            denormalization_context:
                groups: ["session.post"]
        api_quizzes_sessions_get_subresource:
            method: 'GET'
            normalization_context:
                enable_max_depth: true
                groups: ["quiz.sessions.get"]

    itemOperations:
        get:
            normalization_context:
                enable_max_depth: true
                groups: ["session.get"]
        put:
            normalization_context:
                groups: ["session.put"]
            denormalization_context:
                groups: ["session.put"] # Only happens whenever the Hosting party modifies the Quiz's session

