App\Entity\Session:
    collectionOperations:
        get: ~
        post:
            denormalization_context:
                groups: ["session.post"]

    itemOperations:
        get:
            normalization_context:
                groups: ["session.get"]
        put:
            normalization_context:
                groups: ["session.put"]
            denormalization_context:
                groups: ["session.put"] # Only happens whenever the Hosting party modifies the Quiz's session

