App\Entity\User:
    collectionOperations:
        get:
            access_control: 'has_role("ROLE_ADMIN")'
        register:
            path: '/auth/register.{_format}'
            controller: 'App\Controller\Auth\Register'
            method: 'POST'

    properties:
        id: ~
        email: ~
        password:
            readable: false
            writeable: true
        quizzes:
             subresource:
                resourceClass: 'App\Entity\Quiz'
                collection: true
