App\Entity\Activity:
    attributes:
        id:
            groups: ["quiz.sessions.get", "session.get"]
        session:
            groups: ["activity.post", "quiz.sessions.get", "session.get"]
        question:
            groups: ["activity.post", "quiz.sessions.get", "session.get"]
        user:
            groups: ["activity.post", "quiz.sessions.get", "session.get"]
        answer:
            groups: ["activity.post", "session.get"]
        secondsForDecision:
            groups: ["activity.post", "session.get"]
        event:
            groups: ["quiz.sessions.get", "session.get"]
        correct:
            groups: ["quiz.sessions.get", "session.get"]
        created_at:
            groups: ["quiz.sessions.get", "session.get"]

