App\Entity\Answer:
    attributes:
        id:
            groups: ["quiz.put", "quiz.get", "answer.post"]
        text:
            groups: ["quiz.put", "quiz.get", "answer.post"]
        correct:
            groups: ["quiz.put", "quiz.get", "answer.post"]
        question:
            max_depth: 0
            groups: ["quiz.put", "quiz.get", "answer.post"]
