App\Entity\Answer:
    attributes:
        id:
            groups: ["quiz.put", "quiz.get", "answer.post", "session.get"]
        text:
            groups: ["quiz.put", "quiz.get", "answer.post", "answer.put", "session.get"]
        correct:
            groups: ["quiz.put", "quiz.get", "answer.post", "answer.put", "session.get"]
        question:
            max_depth: 0
            groups: ["quiz.put", "quiz.get", "answer.post", "session.get"]
