App\Entity\Question:
    attributes:
        id:
            groups: ["questions", "question"]
        text:
            groups: ["questions", "question"]
        type:
            groups: ["questions", "question"]
        quiz: # If we serialize this property we're likely to run into circular references. Also not necessary as data in front-end is denormalized anyways
        answers:
            groups: ["answers"]
