App\Entity\Question:
    attributes:
        id:
            groups: ["quizzes.get", "quiz.put", "quiz.get", "question.post"]
        text:
            groups: ["quizzes.get", "quiz.put", "quiz.get", "question.post"]
        type:
            groups: ["quizzes.get", "quiz.put", "quiz.get", "question.post"]
        answers:
            max_depth: 0
            groups: ["quiz.put", "quiz.get", "question.post"]
        quiz:
            max_depth: 1
            groups: ["quizzes.get", "quiz.put", "quiz.get", "question.post"]
