App\Entity\Quiz:
    attributes:
        id:
            groups: ["quizzes.get", "quiz.get", "quiz.put"]
        name:
            groups: ["quizzes.get", "quiz.get", "quiz.put"]

        public:
            groups: ["quizzes.get", "quiz.get", "quiz.put"]
        open:
            groups: ["quizzes.get", "quiz.get", "quiz.put"]
        questions:
            max_depth: 1
            groups: ["quizzes.get", "quiz.get", "quiz.put"]