App\Entity\User:
    attributes:
        id:
            groups: ["user.get"]
        email:
            groups: ["user.get", "users.create"]
        password:
            groups: ["user.post", "users.create"]
        roles:
            groups: ["user.get", "user.put"]

